using AutoMapper;
using NeonSuit.RSSReader.Core.DTOs.ArticleTags;
using NeonSuit.RSSReader.Core.Models;

namespace NeonSuit.RSSReader.Core.Profiles
{
    /// <summary>
    /// AutoMapper profile for ArticleTag entity mappings.
    /// Configures transformations between ArticleTag and its related DTOs.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This profile handles mappings for the ArticleTag join entity, which links
    /// articles to tags with additional metadata (who applied it, when, confidence, etc.).
    /// </para>
    /// <para>
    /// Key mappings:
    /// <list type="bullet">
    /// <item><description>ArticleTag → ArticleTagInfoDto: For displaying tag metadata in article details</description></item>
    /// <item><description>CreateArticleTagDto → ArticleTag: For creating new article-tag associations</description></item>
    /// </list>
    /// </para>
    /// <para>
    /// Note: Bulk operations use <see cref="BulkTagOperationDto"/> which is handled directly by services,
    /// not through AutoMapper.
    /// </para>
    /// </remarks>
    public class ArticleTagProfile : Profile
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ArticleTagProfile"/> class.
        /// Configures all mappings between ArticleTag and its DTOs.
        /// </summary>
        public ArticleTagProfile()
        {
            // =========================================================================
            // ENTITY → DTO MAPPINGS (READ OPERATIONS)
            // =========================================================================

            #region ArticleTag → ArticleTagInfoDto


            CreateMap<ArticleTag, ArticleTagInfoDto>()
                .ForMember(dest => dest.TagName,
                    opt => opt.MapFrom(src => src.Tag == null ? string.Empty : src.Tag.Name))
                .ForMember(dest => dest.TagColor,
                    opt => opt.MapFrom(src => src.Tag == null ? "#808080" : src.Tag.Color))
                .ForMember(dest => dest.TimeAgo,
                    opt => opt.MapFrom(src => GetTimeAgo(src.AppliedAt)))
                .ForMember(dest => dest.RuleName,
                    opt => opt.MapFrom(src => src.Rule == null ? null : src.Rule.Name))
                .ForMember(dest => dest.AppliedBy,
                    opt => opt.MapFrom(src => src.AppliedBy))
                .ForMember(dest => dest.AppliedAt,
                    opt => opt.MapFrom(src => src.AppliedAt))
                .ForMember(dest => dest.Confidence,
                    opt => opt.MapFrom(src => src.Confidence))
                .ForMember(dest => dest.TagId,
                    opt => opt.MapFrom(src => src.TagId));

            #endregion

            // =========================================================================
            // DTO → ENTITY MAPPINGS (WRITE OPERATIONS)
            // =========================================================================

            #region CreateArticleTagDto → ArticleTag

            CreateMap<CreateArticleTagDto, ArticleTag>()
                .ForMember(dest => dest.Id,
                    opt => opt.Ignore()) // Auto-generated by database
                .ForMember(dest => dest.AppliedAt,
                    opt => opt.MapFrom(_ => DateTime.UtcNow))
                .ForMember(dest => dest.Article,
                    opt => opt.Ignore()) // Set by EF Core
                .ForMember(dest => dest.Tag,
                    opt => opt.Ignore()) // Set by EF Core
                .ForMember(dest => dest.Rule,
                    opt => opt.Ignore()); // Set by EF Core if RuleId is provided

            #endregion

            // Note: BulkTagOperationDto is not mapped through AutoMapper as it's
            // used directly by services for batch operations.
        }

        #region Private Helper Methods

        /// <summary>
        /// Generates a human-readable "time ago" string from a UTC date.
        /// </summary>
        /// <param name="date">The UTC date to format.</param>
        /// <returns>A string like "Just now", "5 min ago", "2 hours ago", etc.</returns>
        private static string GetTimeAgo(DateTime date)
        {
            var diff = DateTime.UtcNow - date;

            return diff.TotalMinutes switch
            {
                < 1 => "Just now",
                < 60 => $"{(int)diff.TotalMinutes} min ago",
                < 1440 => $"{(int)diff.TotalHours} hours ago",
                _ => $"{(int)diff.TotalDays} days ago"
            };
        }

        #endregion
    }
}