<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.12"><PrivateAssets>all</PrivateAssets></PackageReference>
    <None Include="Database\RSSReaderDbContext.Configuration.cs" />
  </ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="NeonSuit.RSSReader.Setup" />
    <InternalsVisibleTo Include="NeonSuit.RSSReader.Tests.Unit" />
    <InternalsVisibleTo Include="NeonSuit.RSSReader.Tests.Integration" />
	</ItemGroup>



  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.12" />
    <PackageReference Include="Serilog" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NeonSuit.RSSReader.Core\NeonSuit.RSSReader.Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

</Project>
