namespace NeonSuit.RSSReader.Core.Enums
{
    /// <summary>
    /// Represents the different types of user interactions or resolutions applied to a notification 
    /// generated by the RSS reader application (new articles, feed errors, sync events, etc.).
    /// </summary>
    /// <remarks>
    /// <para>
    /// This enumeration tracks how (or if) the user responded to a displayed notification.
    /// It is used to:
    /// </para>
    /// <list type="bullet">
    ///     <item>Update notification state in the UI and persistence layer</item>
    ///     <item>Collect analytics on user behavior with notifications</item>
    ///     <item>Prevent duplicate notifications for the same event</item>
    ///     <item>Trigger secondary actions (e.g., mark article as read when notification is clicked)</item>
    ///     <item>Support snooze/dismiss/archive workflows</item>
    /// </list>
    ///
    /// <para>
    /// Notification actions are typically recorded when the user interacts with a system notification
    /// (toast, banner, tray icon popup) or with in-app notification elements.
    /// </para>
    ///
    /// <para>
    /// Business rules and behavioral implications:
    /// </para>
    /// <list type="bullet">
    ///     <item><see cref="None"/> indicates the notification is still visible/unresolved — it may continue
    ///           to appear in notification center or re-surface on app open.</item>
    ///     <item>Most actions (<see cref="Clicked"/>, <see cref="Dismissed"/>, etc.) are terminal:
    ///           they mark the notification as handled and prevent further automatic re-display
    ///           for the same underlying event.</item>
    ///     <item><see cref="Snoozed"/> is temporary — the notification is hidden for a user-configured
    ///           period (e.g., 1 hour, until tomorrow) and may reappear afterward.</item>
    ///     <item>Actions like <see cref="MarkAsRead"/>, <see cref="Star"/>, <see cref="Archive"/> often
    ///           cascade to the related article/feed (e.g., clicking a "new article" notification
    ///           may set <see cref="NotificationAction.Clicked"/> and simultaneously mark the article
    ///           as Read).</item>
    ///     <item><see cref="Custom1"/> and <see cref="Custom2"/> are reserved for future or
    ///           context-specific buttons defined per notification type (e.g., "Unsubscribe",
    ///           "Mute feed", "Share", etc.). Their exact meaning depends on the notification payload.</item>
    ///     <item>Once an action other than <see cref="None"/> or <see cref="Snoozed"/> is recorded,
    ///           the notification should no longer be re-presented automatically for the same trigger.</item>
    /// </list>
    /// </remarks>
    public enum NotificationAction
    {
        /// <summary>
        /// The notification has not been interacted with yet (still visible or pending in notification center).
        /// </summary>
        /// <remarks>
        /// <para>Behavior:</para>
        /// <list type="bullet">
        ///     <item>Notification remains eligible for display/re-display.</item>
        ///     <item>Default initial state when a notification is first created.</item>
        /// </list>
        /// </remarks>
        None = 0,

        /// <summary>
        /// The user clicked/tapped the main body of the notification.
        /// </summary>
        /// <remarks>
        /// <para>Behavior:</para>
        /// <list type="bullet">
        ///     <item>Typically navigates to the related content (article, feed, settings page).</item>
        ///     <item>Often triggers secondary actions (e.g., mark article as read).</item>
        ///     <item>Marks notification as resolved.</item>
        /// </list>
        /// </remarks>
        Clicked = 1,

        /// <summary>
        /// The user explicitly dismissed or closed the notification (swipe away, close button, etc.).
        /// </summary>
        /// <remarks>
        /// <para>Behavior:</para>
        /// <list type="bullet">
        ///     <item>Removes the notification from view and prevents automatic re-showing for this event.</item>
        ///     <item>No secondary actions are triggered.</item>
        /// </list>
        /// </remarks>
        Dismissed = 2,

        /// <summary>
        /// The user chose to snooze/postpone the notification.
        /// </summary>
        /// <remarks>
        /// <para>Behavior:</para>
        /// <list type="bullet">
        ///     <item>Hides the notification temporarily (duration configured by user or default).</item>
        ///     <item>Notification may reappear after snooze period expires.</item>
        ///     <item>Does not resolve the underlying event permanently.</item>
        /// </list>
        /// </remarks>
        Snoozed = 3,

        /// <summary>
        /// User clicked a custom action button to archive the related article/feed item.
        /// </summary>
        /// <remarks>
        /// <para>Behavior:</para>
        /// <list type="bullet">
        ///     <item>Applies archive status to the associated article.</item>
        ///     <item>Marks notification as handled.</item>
        /// </list>
        /// </remarks>
        Archive = 4,

        /// <summary>
        /// User clicked a custom action button to mark the related article as read.
        /// </summary>
        /// <remarks>
        /// <para>Behavior:</para>
        /// <list type="bullet">
        ///     <item>Sets article status to Read (if applicable).</item>
        ///     <item>Resolves the notification.</item>
        /// </list>
        /// </remarks>
        MarkAsRead = 5,

        /// <summary>
        /// User clicked a custom action button to star/favorite the related article.
        /// </summary>
        /// <remarks>
        /// <para>Behavior:</para>
        /// <list type="bullet">
        ///     <item>Sets article status to Starred (or adds star flag).</item>
        ///     <item>Resolves the notification.</item>
        /// </list>
        /// </remarks>
        Star = 6,

        /// <summary>
        /// User clicked a custom action button to open the article/feed in the system web browser.
        /// </summary>
        /// <remarks>
        /// <para>Behavior:</para>
        /// <list type="bullet">
        ///     <item>Launches external browser with the content URL.</item>
        ///     <item>May or may not mark content as read (configurable).</item>
        ///     <item>Resolves the notification.</item>
        /// </list>
        /// </remarks>
        OpenInBrowser = 7,

        /// <summary>
        /// First reserved slot for a context-specific custom action button.
        /// </summary>
        /// <remarks>
        /// <para>Meaning depends on notification type (e.g., "Mute this feed", "Unsubscribe", "Share", etc.).</para>
        /// <para>Should be documented per notification category when used.</para>
        /// </remarks>
        Custom1 = 8,

        /// <summary>
        /// Second reserved slot for a context-specific custom action button.
        /// </summary>
        /// <remarks>
        /// <para>Meaning depends on notification type (e.g., "View all in feed", "Report issue", etc.).</para>
        /// <para>Should be documented per notification category when used.</para>
        /// </remarks>
        Custom2 = 9
    }
}